name: Solar System Workflow

on: 
  workflow_dispatch:
  push:

jobs:
  testing:
    runs-on: [self-hosted,Linux,X64]
    steps:
      - run: echo "I am on Self-Hosted Runner"
      
      - run: sleep 600s