name: Solar System Workflow

on: 
  workflow_dispatch:
  push:

jobs:
    
  building:
    runs-on: ubuntu-latest
    steps:
      - name: Building Docker Image
        run: docker build -t ci-learning . 

      - name: Saving Image
        run: docker save ci-learning -o ci-learning.jar

      - name: Uploading Image
        use: actions/upload-artifact@v7
        with: 
          name: ci-learning-image
          path: ./ci-learning.jar

    